version: '3.8'

services:
  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=YourStore
      - POSTGRES_USER=jzlbornoz
      - POSTGRES_PASSWORD=fatima17
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
  mysql-db:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=YourStore
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=fatima17
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=fatima17
      - PMA_HOST=mysql-db
    ports:
      - 8080:80


